package mocks

import (
	"github.com/stretchr/testify/mock"
	"golang.org/x/net/context"

	base "github.com/Permify/permify/pkg/pb/base/v1"
)

// SchemaReader is an autogenerated mock type for the SchemaReader type
type SchemaReader struct {
	mock.Mock
}

// ReadSchema - Reads a new schema from repository
func (_m *SchemaReader) ReadSchema(ctx context.Context, tenantID, version string) (schema *base.SchemaDefinition, err error) {
	ret := _m.Called(tenantID, version)

	var r0 *base.SchemaDefinition
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *base.SchemaDefinition); ok {
		r0 = rf(ctx, tenantID, version)
	} else {
		r0 = ret.Get(0).(*base.SchemaDefinition)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, version)
	} else {
		if e, ok := ret.Get(1).(error); ok {
			r1 = e
		} else {
			r1 = nil
		}
	}

	return r0, r1
}

// ReadSchemaDefinition - Reads a Schema Definition from repository
func (_m *SchemaReader) ReadSchemaDefinition(ctx context.Context, tenantID, entityType, version string) (definition *base.EntityDefinition, v string, err error) {
	ret := _m.Called(tenantID, entityType, version)

	var r0 *base.EntityDefinition
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *base.EntityDefinition); ok {
		r0 = rf(ctx, tenantID, entityType, version)
	} else {
		r0 = ret.Get(0).(*base.EntityDefinition)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) string); ok {
		r1 = rf(ctx, tenantID, entityType, version)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, tenantID, entityType, version)
	} else {
		if e, ok := ret.Get(2).(error); ok {
			r2 = e
		} else {
			r2 = nil
		}
	}

	return r0, r1, r2
}

// HeadVersion - Reads the latest version from the repository.
func (_m *SchemaReader) HeadVersion(ctx context.Context, tenantID string) (version string, err error) {
	ret := _m.Called(tenantID)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		if e, ok := ret.Get(1).(error); ok {
			r1 = e
		} else {
			r1 = nil
		}
	}

	return r0, r1
}
