export const SET_SCHEMA = 'SET_SCHEMA';
export const SET_RELATIONSHIPS = 'SET_RELATIONSHIPS';
export const ADD_RELATIONSHIPS = 'ADD_RELATIONSHIPS';
export const SET_ASSERTIONS = 'SET_ASSERTIONS';
export const ADD_ASSERTIONS = 'ADD_ASSERTIONS';
